from __future__ import annotations

import random
from datetime import datetime, timezone


def _random_multiplier(low: float, high: float) -> float:
    value = random.uniform(low, high)
    if value < 2:
        return round(value, 2)
    if value < 5:
        return round(value, 1)
    return round(value)


def _pick_session_window() -> str:
    minute = datetime.now(timezone.utc).minute
    if minute < 20:
        return "opening"
    if minute < 40:
        return "mid-session"
    return "closing"


def generate_quick_signal() -> str:
    target = _random_multiplier(1.25, 2.85)
    risk = random.choice(["Low", "Medium", "Medium"])
    return (
        "⚡ **Quick Signal**\n\n"
        f"🎯 Cashout at: **{target:.2f}x**\n"
        f"📊 Risk: **{risk}**\n"
        f"⏱ Window: next **{random.randint(2, 5)}** rounds\n\n"
        "follow /strategy must to win 100% of the time"

    )


def generate_personal_signal(platform_id: str | None = None) -> str:
    target = _random_multiplier(1.35, 4.2)
    safe_exit = round(target * random.uniform(0.72, 0.88), 2)
    rounds = random.randint(3, 8)
    session = _pick_session_window()
    confidence = random.randint(58, 91)
    player = f"`{platform_id}`" if platform_id else "guest"

    return (
        "🎯 **Personal Signal**\n\n"
        f"🆔 Player: {player}\n"
        f"🎯 Target: **{target:.2f}x**\n"
        f"🛡 Safe exit: **{safe_exit:.2f}x**\n"
        f"📈 Confidence: **{confidence}%**\n"
        f"⏱ Best window: **{rounds}** rounds ({session})\n"
        f"💡 Pattern: {random.choice(['steady climb', 'late spike', 'early pullback', 'flat build'])}\n\n"
        "⚠️ This Signal is Generated By AI\n\n"
        "Check 100% Win method here 👉 /strategy and play accordingly\n\n"

    )
